name: Frontend Tests
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened", "ready_for_review"]
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - ".dockerignore"

permissions:
  contents: read
  pull-requests: write

jobs:
  # storybook:
  #   if: github.event.pull_request.draft == false
  #   name: Storybook (visual tests)
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v3

  #     - name: Set up environment
  #       uses: ./.github/actions/ci-env

  #     - name: Run Storybook tests
  #       run: npm run test-storybook:ci

  vitest:
    if: github.event.pull_request.draft == false
    name: Vitest (unit tests)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run React unit tests
        run: pnpm test

      - name: Report test coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all
          json-summary-path: ./coverage/vitest/coverage-summary.json
          json-final-path: ./coverage/vitest/coverage-final.json

  lint:
    if: github.event.pull_request.draft == false
    name: ESLint (linting)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run eslint
        run: pnpm lint

  prettier:
    if: github.event.pull_request.draft == false
    name: Prettier (formatting)
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Run Prettier
        run: npx prettier --check .

  build:
    name: tsc (build)
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/ci-env

      - name: Build project
        run: pnpm build
